ewelink:
  region: eu
  email: maxpavlov.dp@gmail.com
  password: Nopassword1
  countryCode: "+380"
  appId: YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q
  appSecret: 4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa

deviceId: 10013bb124

device:
  chargeTimeSecs: 1200

spring:
  datasource:
    url: jdbc:tc:postgresql:14.4://localhost:5432/test_database
    username: user
    password: password

flyway:
  locations: "classpath:db/migration/pg"
