ewelink:
  region: eu
  email: eskimorollerr@gmail.com
  password: Nopassword1
  countryCode: "+380"
  appId: YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q
  appSecret: 4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa

deviceId: 10013bb124

device:
  freeChargeSecs: 1200

station:
  scan-delay-ms: 3000
  scan-batch-size: 5
  scan-threads: 1
  scan-interval-ms: 3000

spring:

  datasource:
    url: jdbc:tc:postgresql:14.4://localhost:5432/test_database
    username: user
    password: password

  flyway:
    locations: 'classpath:db/migration/postgres/common,/db/migration/postgres/local'

monobank:
  token: "uZR_Cp6hs2TiuLUIPEXKk0pWeKbwy5tNAWmhJg4DU5Zg"
  callBackHost: "49.12.19.42"
